## Import Library

In [1]:
import numpy as np

## Array

In [2]:
# numpy array
a = [1,2,3,4]
np.array(a)

array([1, 2, 3, 4])

In [3]:
#type
b = np.array([1,2,3,4])
b.dtype

dtype('int64')

In [2]:
c = np.array([[1,2,3],
              [4,5,6]])
type(c)

numpy.ndarray

In [8]:
a= np.array(['1','1.2','5.6'])
a.astype(float)

array([1. , 1.2, 5.6])

In [5]:
# Shape
c.shape

(2, 3)

In [6]:
# dimensions of array
c.ndim

2

In [7]:
# size 
c.size

6

In [7]:
#change many array to 1 array; add oder = 'C'/'F'
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [5]:
c.flatten()

array([1, 2, 3, 4, 5, 6])

In [8]:
d = [1,5,3,1,4,6,6,7,4,4]
np.unique(d)

array([1, 3, 4, 5, 6, 7])

## Zero, Ones and Full

In [8]:
# Zeros(row, column)
zr = np.zeros([2,3])
zr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
on = np.ones([3,2])
on

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Type 
on.dtype

dtype('float64')

In [11]:
# Change type
on = np.ones([3,2], dtype=int)
on.dtype

dtype('int64')

In [12]:
np.full([2,2], 113)

array([[113, 113],
       [113, 113]])

In [7]:
# eye
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [13]:
# seed() to fit random
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [13]:
# normal
np.random.normal(1,10,[3,4])

array([[-4.31983989, 12.58833064, -0.10825656, -0.29972144],
       [18.47951165, -5.06839979, -0.96862575, 17.96263808],
       [-2.04343556, -1.22131263, -8.87240989,  8.28193361]])

In [14]:
# randint
np.random.randint(1,5,[4,5])

array([[2, 4, 4, 4, 4],
       [3, 1, 2, 3, 1],
       [3, 2, 3, 1, 3],
       [4, 4, 2, 1, 3]])

In [15]:
# rand
np.random.rand(3,3)

array([[0.91937803, 0.13529311, 0.65721084],
       [0.96917912, 0.8968833 , 0.19576192],
       [0.4470173 , 0.01344413, 0.86251236]])

In [16]:
# randn
np.random.randn(2,2)

array([[-0.25139784, -0.6996371 ],
       [-1.07153604,  1.38681712]])

## Indexing and Slicing

In [17]:
x1 = np.arange(1,101).reshape(10,10)
x1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [18]:
# get raw 
x1[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# get raw and column
x1[5,4]

55

In [20]:
x1[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
x1[5, :4]

array([51, 52, 53, 54])

In [23]:
# return the size (in bytes)
x1.itemsize

8

In [24]:
x2 = np.random.randint(10, size=10)
x2

array([3, 7, 2, 0, 9, 4, 1, 2, 9, 1])

In [25]:
x2[0:3]

array([3, 7, 2])

In [26]:
# select all table and step is 2
x2[::2]

array([3, 2, 9, 1, 9])

## Arange

In [27]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ar_step = np.arange(5,25, 5)
ar_step

array([ 5, 10, 15, 20])

## Linspace

In [29]:
lin = np.linspace(1,10,5)
lin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Revel and Flatten

In [30]:
# revel
lin.ravel()

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
# flatten
lin.flatten()

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Reshape

In [32]:
ar.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
ar.reshape(1,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

## Transpose

In [34]:
# with T
x = np.array([[1,2], [3,4]])
x.T

array([[1, 3],
       [2, 4]])

In [35]:
# with transpose
np.transpose(x)

array([[1, 3],
       [2, 4]])

## Concatenation

In [36]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [37]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [38]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate((grid, grid))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate((grid, grid), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Vertical and Horizontal

In [42]:
x = np.array([1,2,3])

grid = np.array([[9,8,7],
                [6,5,4]])

In [43]:
# Vertical
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [45]:
# Horizontal
y = np.array([[111],
             [222]])

np.hstack((y, grid))

array([[111,   9,   8,   7],
       [222,   6,   5,   4]])

## Split

In [46]:
x = np.array([1,2,3,11,22,3,2,1])

In [47]:
x1, x2, x3 = np.split(x, [3,5])

In [48]:
x1

array([1, 2, 3])

In [49]:
x2

array([11, 22])

In [50]:
x3

array([3, 2, 1])

In [51]:
slp = np.arange(1, 10)
slp

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.split(slp, [4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

## Mathematic

In [53]:
math_1 = np.arange(3)
math_1

[1, 2, 3, 4]

In [54]:
math_1 + 5

array([5, 6, 7])

In [55]:
math_2 = np.ones([3,3])
math_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
math_1 + math_2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [57]:
 math_1 * math_2

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

## Aggregation

In [58]:
np.array([1,2,3]).sum()

6

In [59]:
massive_array = np.random.random((1000,))

In [60]:
np.mean(massive_array)

0.48710518923584856

In [61]:
np.min(massive_array )

0.00031126235340084296

In [62]:
np.max(massive_array )

0.9999267022785358

## Standard

In [63]:
person_height = [180, 170, 175, 165, 150]

In [64]:
# mean
np.mean(person_height)

168.0

In [65]:
# Standard
person_height = np.array(person_height)
np.std(person_height)

10.295630140987

##  Standard and Deviation

In [66]:
# Variance
np.var(person_height)

106.0

In [67]:
# Standard with formula
np.sqrt(np.var(person_height))

10.295630140987

## Max, Argmax and Min, Argmin

In [68]:
# max_value
person_height.max()

180

In [69]:
# argument_max
person_height.argmax()

0

In [70]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [71]:
# max with axis
grid.max(axis=1)

array([9, 6])

In [72]:
# min_value
person_height.min()

150

In [73]:
# min with axis
grid.min(axis=0)

array([6, 5, 4])

## Sum

In [74]:
arr1 = np.arange(1, 10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
s = np.sum(arr1)
s

45

In [76]:
# sum with axis
sum_axis =np.sum(arr1, axis=0)
sum_axis

array([12, 15, 18])

## Sort

In [77]:
x = np.array([2,1,4,3,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [78]:
np.argsort(x)

array([1, 0, 3, 2, 4])

In [79]:
np.random.seed(42)
MatA = np.random.randint(0,10 ,size =(4,6))

In [80]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [81]:
np.sort(MatA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [82]:
np.sort(MatA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear

In [83]:
A = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [84]:
B = np.array([[6,5],
             [4,3],
             [2,1]])

In [85]:
# dot()
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [86]:
# @
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

## Doc Exercise

In [87]:
import numpy as np

# Random Values 
np.random.seed(0)
sale_amounts = np.random.randint(20, size = [5,3])

In [88]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [96]:
# Insert index and column
import pandas as pd
quarter_sales = pd.DataFrame(sale_amounts, index = ['Sugar', 'Salt', 'Cheese', 'Oil', 'Rice'],
                           columns = ['Jan', 'Junly', 'Sept'])

In [97]:
quarter_sales

Jan  Junly  Sept
Sugar    12     15     0
Salt      3      3     7
Cheese    9     19    18
Oil       4      6    12
Rice      1      6     7

In [98]:
# Get price
prices = np.array([10, 8, 12])

In [99]:
data_price = pd.DataFrame(prices.reshape([1,3]), index = ['Price'], 
                          columns = ['Jan', 'Junly', 'Sept'])

In [100]:
data_price

Jan  Junly  Sept
Price   10      8    12

In [101]:
quarter_sales.shape, data_price.shape

((5, 3), (1, 3))

In [102]:
# doc quarter sales with data price
total_price = quarterly_sales.dot(data_price.T)
total_price

Price
Sugar     240
Salt      138
Cheese    458
Oil       232
Rice      142

In [103]:
# Transpose column = row
quarter_sales.shape, data_price.T.shape

((5, 3), (3, 1))

In [104]:
# Add a column Total price
quarter_sales['Total_prices'] = total_price
quarter_sales

Jan  Junly  Sept  Total_prices
Sugar    12     15     0           240
Salt      3      3     7           138
Cheese    9     19    18           458
Oil       4      6    12           232
Rice      1      6     7           142

In [9]:
# save array
# np.save('my_array.npy', quarter_sales)
# open file
# np.load('my_array.npy')
# save txt
# np.savetxt('my_file.csv', quarter_sales)
# load file
# np.loadtxt('my_file.csv')